name: Test

on:
    push:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm install --legacy-peer-deps
            - run: npm run test
